- name: CCTV-Update-Settings
  hosts: swann-cctv-camera
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: GET Current Camera Settings via the API 
      uri:
        url: https://{{ swann-cctv-cameras }}
        method: GET
        validate_certs: no
        headers:
         X-Auth-Token: "{{ api_key }}"
        status_code: 200
      register: output
          
  - name: printoutput
      ansible.builtin.debug: 
        var: output