---
- hosts: swann-cctv-all
  gather_facts: no

  tasks:
  - name: getMediaConfig
    uri:
      url: http://{{swann-cctv-all}}
      method: GET
      #body_format: json
      validate_certs: no
      headers:
        X-Auth-Token: "{{ api_key }}"
      #body:
      #- [ name, your_username ]
      #- [ password, your_password ]
      #- [ enter, Sign in ]
      status_code: 200
    register: MediaConfig
      
  - name: print MediaConfig
    debug:
      msg: "{{ item }}"
    with_items:
    - "{{ MediaConfig }}"