---
    - name: POST Configuration to Swann CCTV
      hosts: swann_cctv_endpoints
      gather_facts: no
      vars:
        json_file_url: "https://raw.githubusercontent.com/au-uk/SWIFI-4KFLOCAM/main/MediaConfigData.json"
    
      tasks:
        - name: Fetch JSON file
          uri:
            url: "{{ json_file_url }}"
            return_content: yes
          register: json_content
    
        - name: Send POST request to API endpoints
          uri:
            url: "http://{{ swann_cctv_endpoints }}"
            method: POST
            body: "{{ json_content.content | from_json }}"
            body_format: json
            status_code: 200
          register: api_response
    