---
    - name: Swann CCTV MediaConfig
      hosts: swann_cctv_endpoints
      gather_facts: no
      vars:
        json_file_url: "https://raw.githubusercontent.com/au-uk/SWIFI-4KFLOCAM/main/getMediaConfig.json"
    
      tasks:
        - name: Fetch JSON file
          uri:
            url: "{{ json_file_url }}"
            return_content: yes
          register: json_content
          delegate_to: 127.0.0.1
    
        - name: Send POST request to API endpoints
          uri:
            url: "http://{{ inventory_hostname }}:85/API10/setMediaConfig"
            method: POST
            body: "{{ json_content.content | from_json }}"
            body_format: json
            status_code: 200
          register: api_response
          delegate_to: 127.0.0.1